### ISSUE TITLE
submit to hub

### ISSUE THREAD

**Issue by bgrayburn** [ChristianKniep/docker-elk#15]
Thanks for creating this! Any chance you would submit this to the docker hub? Would be much more convenient.

**Comment by ChristianKniep** [comment]
Hey @bgrayburn,

it's already there: https://registry.hub.docker.com/u/qnib/elk/

Cheers

**Comment by bgrayburn** [comment]
thanks, sorry I missed that, any chance you could put a link in the readme, especially since your github namespace (ChristianKniep) is different from you docker hub namespace (qnib)?

**Comment by ChristianKniep** [comment]
done... 
The namespace `qnib` is my generic one on dockerhub, since it's the name of my little shop. 

Thanks for the hint

**Comment by bgrayburn** [comment]
thanks! and thanks again for this most needed image

**Comment by ChristianKniep** [comment]
my pleasure... :)
