### ISSUE TITLE
kibana wont stay up

### ISSUE THREAD

**Issue by akatreyt** [ChristianKniep/docker-elk#19]
Using Kitematic every time I try to start the container I get 

2016-03-02 16:40:52,017 INFO exited: kibana (exit status 1; not expected)
2016-03-02 16:40:53,022 INFO spawned: 'kibana' with pid 584
2016-03-02 16:40:54,024 INFO success: kibana entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-03-02 16:40:55,572 INFO exited: kibana (exit status 1; not expected)

any thoughts?

**Comment by ChristianKniep** [comment]
Currently I am on the run. I'll check on that. Thx for reporting!
Could you please provide the way you started it and how much memory the machine got (less then 2GB led to problems in the past #16, even though it was ES which refused to start).

**Comment by ChristianKniep** [comment]
@akatreyt Any news on that one?

**Comment by akatreyt** [comment]
I just deleted and used another container, sorry I don't have any more info.

**Comment by ChristianKniep** [comment]
Sorry to hear that it does not work. I removed my image and pulled it from the internet.
In my case kibana came up. I still would bet on the lack of RAM.

If you do not pursuit the issue, please close it. 

EDIT: :) I clicked on the wrong button. If you want to follow up, just reopen it.
