### ISSUE TITLE
Support for Kibana 4

### ISSUE THREAD

**Issue by craigedmunds** [ChristianKniep/docker-elk#6]
Now that Kibana 4 has been released it would be great to have the option to use it!

**Comment by ChristianKniep** [comment]
Hey there, sure... will update it. Not sure when I find the time. 
If you like to provide a PR, feel free. :)

**Comment by ChristianKniep** [comment]
Working on it. Will create an image at the weekend, there is a PR waiting to be checked out.
I love OpenSource. :)

**Comment by lhoss** [comment]
So Kibana4 support is in the branch: https://github.com/ChristianKniep/docker-elk/tree/kibana4
1.Any reason why the support is not merged to master?
2. Does master branch have other fixes/updates not in 'kibana4' ?
Thx!

ps: Motivatio
I'm looking for the 'best' ELK Docker setup (with Kibana 4) , comparing with:
https://github.com/deviantony/docker-elk-kibana

Ideally I'ld like a Docker image, delegating main setup to ansible (in case we will deploy prod setup, not in Docker), for ex using: https://github.com/bakhti/ansible-elk

**Comment by ChristianKniep** [comment]
Moin @lhoss,
it's not merge because I hadn't had time to play around and get used to kibana4. 
For me kibana3 is still set as the default. Furthermore I am moving away from a ELK image, but split the E, the L and the K up to have a better split of concern.

**Comment by ChristianKniep** [comment]
done
