### ISSUE TITLE
Redirect root-uri to /kibana

### ISSUE THREAD

**Issue by ChristianKniep** [ChristianKniep/docker-elk#9]
As indicated in the PR #4, the root of nginx should be forwarded to /kibana.

**Comment by 4thAce** [comment]
Yes, please put this in. It took me a couple of hours to find this out on my own because I thought the 403 errors were coming from the basic authentication

**Comment by ChristianKniep** [comment]
Sorry @4thAce,

that's a pity. I will update it right away...

**Comment by ChristianKniep** [comment]
Could you please check on the new build?

**Comment by 4thAce** [comment]
It comes up cleanly, thanks!

**Comment by ChristianKniep** [comment]
I have to thank you to push me to do it... :+1:
